version: '2'

services:
  mongodb:
    image: mongo:4.1.9
    ports:
    - "27017:27017"
    volumes:
    - './mongo-data:/data/db'

#  service:
#    image: dua-lupa:latest
#    environment:
#      SPRING_PROFILES_ACTIVE: prod
#    ports:
#    - 8080:8080
#    depends_on:
#    - mongodb